import type { CampaignConfig, Lead } from './types'

export const initialLeads: Lead[] = []

export const defaultCampaignConfig: CampaignConfig = {
  instructions: '',
  dialerProvider: 'speak',
  personalPhoneInbound: {
    enabled: false,
    eligibilityScope: 'source',
    sourceId: '',
    contactIds: [],
    smartViewIds: [],
  },
  calltoolsAgentBinding: {
    enabled: false,
    mode: 'phone_as_agent',
    webCallbackId: '',
    contactMatchMode: 'calltools_contact_id_then_phone',
    provisioningStatus: 'unconfigured',
    mediaGatewayStatus: 'unconfigured',
  },
  voiceRuntimeProvider: 'hume',
  eviVersion: '3',
  humeConfigId: '',
  inworldConfigId: 'inworld-realtime',
  xaiConfigId: 'xai-realtime',
  voice: '',
  humeVoiceId: '',
  humeVoiceName: 'Speak Voice',
  humeVoiceProvider: 'CUSTOM_VOICE',
  inworldVoiceName: 'Dennis',
  inworldVoiceId: 'Dennis',
  inworldVoiceProvider: 'INWORLD_SYSTEM',
  xaiVoiceName: 'Eve',
  xaiVoiceId: 'eve',
  xaiVoiceProvider: 'XAI_BUILTIN',
  supplementalLlm: 'Claude Sonnet 4.6',
  languageModelMode: 'hume',
  languageModelProvider: 'ANTHROPIC',
  languageModelResource: 'claude-sonnet-4-6',
  languageModelTemperature: 1,
  codexAuthModel: 'gpt-5.5',
  codexReasoningEffort: 'none',
  codexFastMode: true,
  allowShortResponses: false,
  promptExpansionEnabled: false,
  inactivityTimeoutEnabled: true,
  inactivityTimeoutSeconds: 120,
  maxDurationTimeoutEnabled: true,
  maxDurationTimeoutSeconds: 1800,
  turnDetectionEnabled: true,
  endOfTurnSilenceMs: 500,
  speechDetectionThreshold: 0.58,
  prefixPaddingMs: 300,
  interruptionEnabled: true,
  minInterruptionMs: 550,
  nudgesEnabled: true,
  nudgesIntervalSeconds: 4,
  eviStartsConversation: false,
  resumeConversationMessageEnabled: true,
  resumeConversationMessage: '',
  inactivityMessageEnabled: false,
  inactivityMessage: '',
  maxDurationMessageEnabled: false,
  maxDurationMessage: '',
  webSearchEnabled: false,
  hangUpEnabled: true,
  inworldRealtimeModel: 'google-ai-studio/gemini-2.5-flash',
  inworldSttModel: 'inworld/inworld-stt-1',
  inworldTtsModel: 'inworld-tts-2',
  inworldLanguage: 'en-US',
  inworldTurnDetectionMode: 'semantic_vad',
  inworldTurnEagerness: 'high',
  inworldTtsDeliveryMode: 'CREATIVE',
  inworldTtsSegmenterStrategy: 'full_turn',
  inworldTtsSteeringHandling: 'emit_once',
  inworldTtsConversationalEnabled: false,
  inworldTtsUserTurnMode: 'both',
  inworldVoiceSteeringEnabled: true,
  inworldResponsivenessInitialWaitMs: 600,
  inworldResponsivenessHardDeadlineMs: 1200,
  inworldBackchannelEnabled: false,
  inworldResponsivenessEnabled: false,
  inworldMemoryEnabled: false,
  inworldOutputSampleRate: 16000,
  xaiRealtimeModel: 'grok-voice-latest',
  xaiReasoningEffort: 'none',
  xaiLanguageHint: 'en',
  xaiKeyterms: [],
  xaiVoiceSpeed: 1,
  xaiResumptionEnabled: true,
  xaiToolCallingEnabled: true,
  xaiOutputSampleRate: 16000,
  verboseTranscription: true,
  audioEncoding: 'linear16',
  phoneAudioMode: 'optimized',
  phoneOutputGain: 0.72,
  phoneOutputPeak: 0.58,
  sampleRate: 16000,
  telnyxCallerId: '+1 your phone number',
  telnyxConnectionId: 'Phone connection ID',
  telnyxStreamCodec: 'L16',
  callWindow: '10:00 AM - 6:00 PM local',
  maxConcurrent: 1,
  useConfigPrompt: true,
  useConfigTools: true,
  autoStartGreeting: false,
}
