import type { Lead } from './types'

export const demoLeads: Lead[] = [
  {
    id: 'demo-enterprise-001',
    firstName: 'Maya',
    lastName: 'Chen',
    name: 'Maya Chen',
    company: 'Orion Systems Group',
    phone: '+17045550118',
    email: 'maya.chen@orion.example',
    state: 'NC',
    tags: ['enterprise', 'priority', 'renewal'],
    score: 94,
    status: 'ready',
    lastCall: 'Never',
    notes:
      'Enterprise account reviewing renewal options. Confirm the best contact channel before sending any follow-up.',
  },
  {
    id: 'demo-startup-002',
    firstName: 'Evan',
    lastName: 'Brooks',
    name: 'Evan Brooks',
    company: 'Northline Robotics',
    phone: '+19195550177',
    email: 'evan@northline.example',
    state: 'TX',
    tags: ['startup', 'demo-request'],
    score: 88,
    status: 'follow-up',
    lastCall: 'Yesterday',
    notes:
      'Asked for a concise product walkthrough and pricing recap. Keep the next call under ten minutes.',
  },
  {
    id: 'demo-founder-003',
    firstName: 'Priya',
    lastName: 'Raman',
    name: 'Priya Raman',
    company: 'Solo Ledger Studio',
    phone: '+13125550141',
    email: 'priya@sololedger.example',
    state: 'IL',
    tags: ['sole-proprietor', 'trial'],
    score: 82,
    status: 'ready',
    lastCall: 'Never',
    notes:
      'Independent consultant comparing tools. Ask about current call volume before recommending a plan.',
  },
  {
    id: 'demo-services-004',
    firstName: 'Noah',
    lastName: 'Patel',
    name: 'Noah Patel',
    company: 'Fieldstone Advisory',
    phone: '+14155550164',
    email: 'noah@fieldstone.example',
    state: 'CA',
    tags: ['small-business', 'implementation'],
    score: 79,
    status: 'ready',
    lastCall: 'Never',
    notes:
      'Wants to understand handoff from AI agent to human operator. Confirm workflow before scheduling setup.',
  },
  {
    id: 'demo-health-005',
    firstName: 'Amara',
    lastName: 'Cole',
    name: 'Amara Cole',
    company: 'BrightPath Wellness',
    phone: '+12125550132',
    email: 'amara@brightpath.example',
    state: 'NY',
    tags: ['operations', 'callback'],
    score: 76,
    status: 'no-answer',
    lastCall: '2 days ago',
    notes:
      'No answer on first attempt. Try early afternoon and keep the opener focused on appointment follow-up automation.',
  },
  {
    id: 'demo-retail-006',
    firstName: 'Luis',
    lastName: 'Moreno',
    name: 'Luis Moreno',
    company: 'Harbor Market Co.',
    phone: '+16175550109',
    email: 'luis@harbormarket.example',
    state: 'MA',
    tags: ['retail', 'seasonal'],
    score: 72,
    status: 'voicemail',
    lastCall: 'Today',
    notes:
      'Left voicemail about seasonal outreach support. Do not mark complete until Luis confirms interest.',
  },
]
